//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NakamaAgentService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemPlataform", Namespace="http://schemas.datacontract.org/2004/07/Nakama.Core.Model.Common")]
    public partial class SystemPlataform : object
    {
        
        private int SystemPlataformIDField;
        
        private string SystemPlataformNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SystemPlataformID
        {
            get
            {
                return this.SystemPlataformIDField;
            }
            set
            {
                this.SystemPlataformIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SystemPlataformName
        {
            get
            {
                return this.SystemPlataformNameField;
            }
            set
            {
                this.SystemPlataformNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemPlataformList", Namespace="http://schemas.datacontract.org/2004/07/Nakama.Core.Model.Common")]
    public partial class SystemPlataformList : object
    {
        
        private NakamaAgentService.SystemPlataform[] SystemsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NakamaAgentService.SystemPlataform[] Systems
        {
            get
            {
                return this.SystemsField;
            }
            set
            {
                this.SystemsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MarketGroup", Namespace="http://schemas.datacontract.org/2004/07/Nakama.Core.Model.Market")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.MarketSport))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.AgentMarketSportGroup))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.MarketCategory))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.MarketTournament))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.AgentMarketTournamentGroup))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.AgentMarketCategoryGroup))]
    public partial class MarketGroup : object
    {
        
        private bool IsForAllPlayersField;
        
        private bool IsForAllSubAgentsField;
        
        private NakamaAgentService.MarketLimit[] LimitsField;
        
        private int SystemPlataformIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsForAllPlayers
        {
            get
            {
                return this.IsForAllPlayersField;
            }
            set
            {
                this.IsForAllPlayersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsForAllSubAgents
        {
            get
            {
                return this.IsForAllSubAgentsField;
            }
            set
            {
                this.IsForAllSubAgentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NakamaAgentService.MarketLimit[] Limits
        {
            get
            {
                return this.LimitsField;
            }
            set
            {
                this.LimitsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SystemPlataformID
        {
            get
            {
                return this.SystemPlataformIDField;
            }
            set
            {
                this.SystemPlataformIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MarketSport", Namespace="http://schemas.datacontract.org/2004/07/Nakama.Core.Model.Market")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.AgentMarketSportGroup))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.MarketCategory))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.MarketTournament))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.AgentMarketTournamentGroup))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.AgentMarketCategoryGroup))]
    public partial class MarketSport : NakamaAgentService.MarketGroup
    {
        
        private int SportIDField;
        
        private string SportsNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SportID
        {
            get
            {
                return this.SportIDField;
            }
            set
            {
                this.SportIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SportsName
        {
            get
            {
                return this.SportsNameField;
            }
            set
            {
                this.SportsNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AgentMarketSportGroup", Namespace="http://schemas.datacontract.org/2004/07/Nakama.Core.Model.Shared.Market.Limits.Ag" +
        "ents")]
    public partial class AgentMarketSportGroup : NakamaAgentService.MarketSport
    {
        
        private string AgentIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AgentID
        {
            get
            {
                return this.AgentIDField;
            }
            set
            {
                this.AgentIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MarketCategory", Namespace="http://schemas.datacontract.org/2004/07/Nakama.Core.Model.Market")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.MarketTournament))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.AgentMarketTournamentGroup))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.AgentMarketCategoryGroup))]
    public partial class MarketCategory : NakamaAgentService.MarketSport
    {
        
        private int CategoryIDField;
        
        private string CategoryNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryID
        {
            get
            {
                return this.CategoryIDField;
            }
            set
            {
                this.CategoryIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryName
        {
            get
            {
                return this.CategoryNameField;
            }
            set
            {
                this.CategoryNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MarketTournament", Namespace="http://schemas.datacontract.org/2004/07/Nakama.Core.Model.Market")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.AgentMarketTournamentGroup))]
    public partial class MarketTournament : NakamaAgentService.MarketCategory
    {
        
        private int TournamentIDField;
        
        private string TournamentNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TournamentID
        {
            get
            {
                return this.TournamentIDField;
            }
            set
            {
                this.TournamentIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TournamentName
        {
            get
            {
                return this.TournamentNameField;
            }
            set
            {
                this.TournamentNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AgentMarketTournamentGroup", Namespace="http://schemas.datacontract.org/2004/07/Nakama.Core.Model.Market.Limits.Agents")]
    public partial class AgentMarketTournamentGroup : NakamaAgentService.MarketTournament
    {
        
        private string AgentIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AgentID
        {
            get
            {
                return this.AgentIDField;
            }
            set
            {
                this.AgentIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AgentMarketCategoryGroup", Namespace="http://schemas.datacontract.org/2004/07/Nakama.Core.Model.Market.Limits.Agents")]
    public partial class AgentMarketCategoryGroup : NakamaAgentService.MarketCategory
    {
        
        private string AgentIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AgentID
        {
            get
            {
                return this.AgentIDField;
            }
            set
            {
                this.AgentIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MarketLimit", Namespace="http://schemas.datacontract.org/2004/07/Nakama.Core.Model.Market")]
    public partial class MarketLimit : object
    {
        
        private bool IsActiveField;
        
        private int MarketIDField;
        
        private string MarketNameField;
        
        private double MaxBetField;
        
        private double MaxWinField;
        
        private int SegmentIDField;
        
        private string SegmentNameField;
        
        private string SegmentShortNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive
        {
            get
            {
                return this.IsActiveField;
            }
            set
            {
                this.IsActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MarketID
        {
            get
            {
                return this.MarketIDField;
            }
            set
            {
                this.MarketIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MarketName
        {
            get
            {
                return this.MarketNameField;
            }
            set
            {
                this.MarketNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MaxBet
        {
            get
            {
                return this.MaxBetField;
            }
            set
            {
                this.MaxBetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MaxWin
        {
            get
            {
                return this.MaxWinField;
            }
            set
            {
                this.MaxWinField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SegmentID
        {
            get
            {
                return this.SegmentIDField;
            }
            set
            {
                this.SegmentIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SegmentName
        {
            get
            {
                return this.SegmentNameField;
            }
            set
            {
                this.SegmentNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SegmentShortName
        {
            get
            {
                return this.SegmentShortNameField;
            }
            set
            {
                this.SegmentShortNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MarketGroupFilter", Namespace="http://schemas.datacontract.org/2004/07/Nakama.Extension.Shared.Market")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.MarketSportFilter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.MarketCategoryFilter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.MarketTournamentFilter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.AgentMarketTournamentGroupFilter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.AgentMarketCategoryGroupFilter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.AgentMarketSportGroupFilter))]
    public partial class MarketGroupFilter : object
    {
        
        private bool IsForAllAgentsAndPlayersField;
        
        private NakamaAgentService.MarketLimitFilter[] LimitsField;
        
        private int SystemPlataformIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsForAllAgentsAndPlayers
        {
            get
            {
                return this.IsForAllAgentsAndPlayersField;
            }
            set
            {
                this.IsForAllAgentsAndPlayersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NakamaAgentService.MarketLimitFilter[] Limits
        {
            get
            {
                return this.LimitsField;
            }
            set
            {
                this.LimitsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SystemPlataformID
        {
            get
            {
                return this.SystemPlataformIDField;
            }
            set
            {
                this.SystemPlataformIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MarketSportFilter", Namespace="http://schemas.datacontract.org/2004/07/Nakama.Extension.Shared.Market")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.MarketCategoryFilter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.MarketTournamentFilter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.AgentMarketTournamentGroupFilter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.AgentMarketCategoryGroupFilter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.AgentMarketSportGroupFilter))]
    public partial class MarketSportFilter : NakamaAgentService.MarketGroupFilter
    {
        
        private int SportIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SportID
        {
            get
            {
                return this.SportIDField;
            }
            set
            {
                this.SportIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MarketCategoryFilter", Namespace="http://schemas.datacontract.org/2004/07/Nakama.Extension.Shared.Market")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.MarketTournamentFilter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.AgentMarketTournamentGroupFilter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.AgentMarketCategoryGroupFilter))]
    public partial class MarketCategoryFilter : NakamaAgentService.MarketSportFilter
    {
        
        private int CategoryIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryID
        {
            get
            {
                return this.CategoryIDField;
            }
            set
            {
                this.CategoryIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MarketTournamentFilter", Namespace="http://schemas.datacontract.org/2004/07/Nakama.Extension.Shared.Market")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.AgentMarketTournamentGroupFilter))]
    public partial class MarketTournamentFilter : NakamaAgentService.MarketCategoryFilter
    {
        
        private int TournamentIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TournamentID
        {
            get
            {
                return this.TournamentIDField;
            }
            set
            {
                this.TournamentIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AgentMarketTournamentGroupFilter", Namespace="http://schemas.datacontract.org/2004/07/Nakama.Extension.Shared.Market.Limits.Age" +
        "nts")]
    public partial class AgentMarketTournamentGroupFilter : NakamaAgentService.MarketTournamentFilter
    {
        
        private string AgentIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AgentID
        {
            get
            {
                return this.AgentIDField;
            }
            set
            {
                this.AgentIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AgentMarketCategoryGroupFilter", Namespace="http://schemas.datacontract.org/2004/07/Nakama.Extension.Shared.Market.Limits.Age" +
        "nts")]
    public partial class AgentMarketCategoryGroupFilter : NakamaAgentService.MarketCategoryFilter
    {
        
        private string AgentIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AgentID
        {
            get
            {
                return this.AgentIDField;
            }
            set
            {
                this.AgentIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AgentMarketSportGroupFilter", Namespace="http://schemas.datacontract.org/2004/07/Nakama.Extension.Shared.Market.Limits.Age" +
        "nts")]
    public partial class AgentMarketSportGroupFilter : NakamaAgentService.MarketSportFilter
    {
        
        private string AgentIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AgentID
        {
            get
            {
                return this.AgentIDField;
            }
            set
            {
                this.AgentIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MarketLimitFilter", Namespace="http://schemas.datacontract.org/2004/07/Nakama.Extension.Shared.Market")]
    public partial class MarketLimitFilter : object
    {
        
        private bool IsActiveField;
        
        private int MarketIDField;
        
        private System.Nullable<double> MaxBetField;
        
        private double MaxWinField;
        
        private int SegmentIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive
        {
            get
            {
                return this.IsActiveField;
            }
            set
            {
                this.IsActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MarketID
        {
            get
            {
                return this.MarketIDField;
            }
            set
            {
                this.MarketIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> MaxBet
        {
            get
            {
                return this.MaxBetField;
            }
            set
            {
                this.MaxBetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MaxWin
        {
            get
            {
                return this.MaxWinField;
            }
            set
            {
                this.MaxWinField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SegmentID
        {
            get
            {
                return this.SegmentIDField;
            }
            set
            {
                this.SegmentIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MarketResponse", Namespace="http://schemas.datacontract.org/2004/07/Nakama.Extension.Shared.Market")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.SystemPlataform))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.SystemPlataformList))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.SystemPlataform[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.AgentMarketCategoryGroup))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.AgentMarketTournamentGroup))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.MarketSport))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.MarketGroup))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.MarketLimit[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.MarketLimit))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.MarketCategory))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.MarketTournament))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.MarketSportFilter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.MarketGroupFilter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.MarketLimitFilter[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.MarketLimitFilter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.MarketCategoryFilter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.MarketTournamentFilter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.HeaderResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.ErrorResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.AgentMarketSportGroupFilter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.AgentMarketCategoryGroupFilter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.AgentMarketTournamentGroupFilter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.AgentMarketSportGroup))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.AgentFilter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.AgentSettingFilter[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.AgentSettingFilter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.AgentFilter[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.AgentResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.Agent))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.AgentList))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.Agent[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.AgentSetting))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.AgentSettingList))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.AgentSetting[]))]
    public partial class MarketResponse : object
    {
        
        private NakamaAgentService.HeaderResponse HeaderField;
        
        private object ResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NakamaAgentService.HeaderResponse Header
        {
            get
            {
                return this.HeaderField;
            }
            set
            {
                this.HeaderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HeaderResponse", Namespace="http://schemas.datacontract.org/2004/07/Nakama.Extension.Shared")]
    public partial class HeaderResponse : object
    {
        
        private NakamaAgentService.ErrorResponse ErrorField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NakamaAgentService.ErrorResponse Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorResponse", Namespace="http://schemas.datacontract.org/2004/07/Nakama.Extension.Shared")]
    public partial class ErrorResponse : object
    {
        
        private int ErrorCodeField;
        
        private string ErrorMessageField;
        
        private string MethodNameField;
        
        private string SourceField;
        
        private string StackTraceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MethodName
        {
            get
            {
                return this.MethodNameField;
            }
            set
            {
                this.MethodNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source
        {
            get
            {
                return this.SourceField;
            }
            set
            {
                this.SourceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace
        {
            get
            {
                return this.StackTraceField;
            }
            set
            {
                this.StackTraceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AgentFilter", Namespace="http://schemas.datacontract.org/2004/07/Nakama.Extension.Shared.Agent")]
    public partial class AgentFilter : object
    {
        
        private string AgentIDField;
        
        private NakamaAgentService.AgentSettingFilter[] AgentSettingsField;
        
        private string AgentTypeField;
        
        private NakamaAgentService.AgentFilter[] SubAgentsField;
        
        private int SystemPlataformIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AgentID
        {
            get
            {
                return this.AgentIDField;
            }
            set
            {
                this.AgentIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NakamaAgentService.AgentSettingFilter[] AgentSettings
        {
            get
            {
                return this.AgentSettingsField;
            }
            set
            {
                this.AgentSettingsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AgentType
        {
            get
            {
                return this.AgentTypeField;
            }
            set
            {
                this.AgentTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NakamaAgentService.AgentFilter[] SubAgents
        {
            get
            {
                return this.SubAgentsField;
            }
            set
            {
                this.SubAgentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SystemPlataformID
        {
            get
            {
                return this.SystemPlataformIDField;
            }
            set
            {
                this.SystemPlataformIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AgentSettingFilter", Namespace="http://schemas.datacontract.org/2004/07/Nakama.Extension.Shared.Agent")]
    public partial class AgentSettingFilter : object
    {
        
        private string AgentIDField;
        
        private int AgentSettingIDField;
        
        private string AgentSettingValueField;
        
        private int PropertyIDField;
        
        private string PropertyNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AgentID
        {
            get
            {
                return this.AgentIDField;
            }
            set
            {
                this.AgentIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AgentSettingID
        {
            get
            {
                return this.AgentSettingIDField;
            }
            set
            {
                this.AgentSettingIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AgentSettingValue
        {
            get
            {
                return this.AgentSettingValueField;
            }
            set
            {
                this.AgentSettingValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PropertyID
        {
            get
            {
                return this.PropertyIDField;
            }
            set
            {
                this.PropertyIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PropertyName
        {
            get
            {
                return this.PropertyNameField;
            }
            set
            {
                this.PropertyNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AgentResponse", Namespace="http://schemas.datacontract.org/2004/07/Nakama.Extension.Shared.Agent")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.SystemPlataform))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.SystemPlataformList))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.SystemPlataform[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.AgentMarketCategoryGroup))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.AgentMarketTournamentGroup))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.MarketSport))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.MarketGroup))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.MarketLimit[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.MarketLimit))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.MarketCategory))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.MarketTournament))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.MarketSportFilter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.MarketGroupFilter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.MarketLimitFilter[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.MarketLimitFilter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.MarketResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.MarketCategoryFilter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.MarketTournamentFilter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.HeaderResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.ErrorResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.AgentMarketSportGroupFilter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.AgentMarketCategoryGroupFilter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.AgentMarketTournamentGroupFilter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.AgentMarketSportGroup))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.AgentFilter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.AgentSettingFilter[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.AgentSettingFilter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.AgentFilter[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.Agent))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.AgentList))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.Agent[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.AgentSetting))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.AgentSettingList))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaAgentService.AgentSetting[]))]
    public partial class AgentResponse : object
    {
        
        private NakamaAgentService.HeaderResponse HeaderField;
        
        private object ResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NakamaAgentService.HeaderResponse Header
        {
            get
            {
                return this.HeaderField;
            }
            set
            {
                this.HeaderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Agent", Namespace="http://schemas.datacontract.org/2004/07/Nakama.Core.Model.Agent")]
    public partial class Agent : object
    {
        
        private string AgentIDField;
        
        private string AgentTypeField;
        
        private string MasterAgentIDField;
        
        private int SystemPlataformIDField;
        
        private string SystemPlataformNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AgentID
        {
            get
            {
                return this.AgentIDField;
            }
            set
            {
                this.AgentIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AgentType
        {
            get
            {
                return this.AgentTypeField;
            }
            set
            {
                this.AgentTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MasterAgentID
        {
            get
            {
                return this.MasterAgentIDField;
            }
            set
            {
                this.MasterAgentIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SystemPlataformID
        {
            get
            {
                return this.SystemPlataformIDField;
            }
            set
            {
                this.SystemPlataformIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SystemPlataformName
        {
            get
            {
                return this.SystemPlataformNameField;
            }
            set
            {
                this.SystemPlataformNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AgentList", Namespace="http://schemas.datacontract.org/2004/07/Nakama.Core.Model.Agent")]
    public partial class AgentList : object
    {
        
        private NakamaAgentService.Agent[] AgentsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NakamaAgentService.Agent[] Agents
        {
            get
            {
                return this.AgentsField;
            }
            set
            {
                this.AgentsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AgentSetting", Namespace="http://schemas.datacontract.org/2004/07/Nakama.Core.Model.Agent")]
    public partial class AgentSetting : object
    {
        
        private string AgentIDField;
        
        private int AgentSettingIDField;
        
        private string AgentSettingValueField;
        
        private int PropertyIDField;
        
        private string PropertyNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AgentID
        {
            get
            {
                return this.AgentIDField;
            }
            set
            {
                this.AgentIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AgentSettingID
        {
            get
            {
                return this.AgentSettingIDField;
            }
            set
            {
                this.AgentSettingIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AgentSettingValue
        {
            get
            {
                return this.AgentSettingValueField;
            }
            set
            {
                this.AgentSettingValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PropertyID
        {
            get
            {
                return this.PropertyIDField;
            }
            set
            {
                this.PropertyIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PropertyName
        {
            get
            {
                return this.PropertyNameField;
            }
            set
            {
                this.PropertyNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AgentSettingList", Namespace="http://schemas.datacontract.org/2004/07/Nakama.Core.Model.Agent")]
    public partial class AgentSettingList : object
    {
        
        private NakamaAgentService.AgentSetting[] AgentSettingsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NakamaAgentService.AgentSetting[] AgentSettings
        {
            get
            {
                return this.AgentSettingsField;
            }
            set
            {
                this.AgentSettingsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NakamaAgentService.IAgentWebService")]
    public interface IAgentWebService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgentWebService/GetAgent", ReplyAction="http://tempuri.org/IAgentWebService/GetAgentResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.SystemPlataform))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.SystemPlataformList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.SystemPlataform[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketCategoryGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketTournamentGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketSport))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketLimit[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketLimit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketCategory))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketTournament))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketSportFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketGroupFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketLimitFilter[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketLimitFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketCategoryFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketTournamentFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.HeaderResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.ErrorResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketSportGroupFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketCategoryGroupFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketTournamentGroupFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketSportGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentSettingFilter[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentSettingFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentFilter[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.Agent))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.Agent[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentSetting))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentSettingList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentSetting[]))]
        System.Threading.Tasks.Task<NakamaAgentService.AgentResponse> GetAgentAsync(object filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgentWebService/GetMasterAgents", ReplyAction="http://tempuri.org/IAgentWebService/GetMasterAgentsResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.SystemPlataform))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.SystemPlataformList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.SystemPlataform[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketCategoryGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketTournamentGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketSport))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketLimit[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketLimit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketCategory))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketTournament))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketSportFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketGroupFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketLimitFilter[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketLimitFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketCategoryFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketTournamentFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.HeaderResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.ErrorResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketSportGroupFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketCategoryGroupFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketTournamentGroupFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketSportGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentSettingFilter[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentSettingFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentFilter[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.Agent))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.Agent[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentSetting))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentSettingList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentSetting[]))]
        System.Threading.Tasks.Task<NakamaAgentService.AgentResponse> GetMasterAgentsAsync(object filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgentWebService/GetSubAgents", ReplyAction="http://tempuri.org/IAgentWebService/GetSubAgentsResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.SystemPlataform))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.SystemPlataformList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.SystemPlataform[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketCategoryGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketTournamentGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketSport))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketLimit[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketLimit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketCategory))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketTournament))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketSportFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketGroupFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketLimitFilter[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketLimitFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketCategoryFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketTournamentFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.HeaderResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.ErrorResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketSportGroupFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketCategoryGroupFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketTournamentGroupFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketSportGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentSettingFilter[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentSettingFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentFilter[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.Agent))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.Agent[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentSetting))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentSettingList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentSetting[]))]
        System.Threading.Tasks.Task<NakamaAgentService.AgentResponse> GetSubAgentsAsync(object filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgentWebService/GetAgentSportMarket", ReplyAction="http://tempuri.org/IAgentWebService/GetAgentSportMarketResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.SystemPlataform))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.SystemPlataformList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.SystemPlataform[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketCategoryGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketTournamentGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketSport))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketLimit[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketLimit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketCategory))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketTournament))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketSportFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketGroupFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketLimitFilter[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketLimitFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketCategoryFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketTournamentFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.HeaderResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.ErrorResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketSportGroupFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketCategoryGroupFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketTournamentGroupFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketSportGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentSettingFilter[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentSettingFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentFilter[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.Agent))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.Agent[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentSetting))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentSettingList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentSetting[]))]
        System.Threading.Tasks.Task<NakamaAgentService.MarketResponse> GetAgentSportMarketAsync(object filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgentWebService/GetAgentCategoryMarket", ReplyAction="http://tempuri.org/IAgentWebService/GetAgentCategoryMarketResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.SystemPlataform))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.SystemPlataformList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.SystemPlataform[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketCategoryGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketTournamentGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketSport))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketLimit[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketLimit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketCategory))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketTournament))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketSportFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketGroupFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketLimitFilter[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketLimitFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketCategoryFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketTournamentFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.HeaderResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.ErrorResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketSportGroupFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketCategoryGroupFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketTournamentGroupFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketSportGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentSettingFilter[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentSettingFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentFilter[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.Agent))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.Agent[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentSetting))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentSettingList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentSetting[]))]
        System.Threading.Tasks.Task<NakamaAgentService.MarketResponse> GetAgentCategoryMarketAsync(object filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgentWebService/GetAgentTournamentMarket", ReplyAction="http://tempuri.org/IAgentWebService/GetAgentTournamentMarketResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.SystemPlataform))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.SystemPlataformList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.SystemPlataform[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketCategoryGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketTournamentGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketSport))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketLimit[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketLimit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketCategory))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketTournament))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketSportFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketGroupFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketLimitFilter[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketLimitFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketCategoryFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketTournamentFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.HeaderResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.ErrorResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketSportGroupFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketCategoryGroupFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketTournamentGroupFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketSportGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentSettingFilter[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentSettingFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentFilter[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.Agent))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.Agent[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentSetting))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentSettingList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentSetting[]))]
        System.Threading.Tasks.Task<NakamaAgentService.MarketResponse> GetAgentTournamentMarketAsync(object filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgentWebService/SetAgentSportMarket", ReplyAction="http://tempuri.org/IAgentWebService/SetAgentSportMarketResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.SystemPlataform))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.SystemPlataformList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.SystemPlataform[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketCategoryGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketTournamentGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketSport))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketLimit[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketLimit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketCategory))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketTournament))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketSportFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketGroupFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketLimitFilter[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketLimitFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketCategoryFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketTournamentFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.HeaderResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.ErrorResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketSportGroupFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketCategoryGroupFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketTournamentGroupFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketSportGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentSettingFilter[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentSettingFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentFilter[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.Agent))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.Agent[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentSetting))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentSettingList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentSetting[]))]
        System.Threading.Tasks.Task<NakamaAgentService.AgentResponse> SetAgentSportMarketAsync(object filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgentWebService/SetAgentCategoryMarket", ReplyAction="http://tempuri.org/IAgentWebService/SetAgentCategoryMarketResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.SystemPlataform))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.SystemPlataformList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.SystemPlataform[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketCategoryGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketTournamentGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketSport))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketLimit[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketLimit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketCategory))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketTournament))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketSportFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketGroupFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketLimitFilter[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketLimitFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketCategoryFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketTournamentFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.HeaderResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.ErrorResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketSportGroupFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketCategoryGroupFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketTournamentGroupFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketSportGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentSettingFilter[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentSettingFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentFilter[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.Agent))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.Agent[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentSetting))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentSettingList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentSetting[]))]
        System.Threading.Tasks.Task<NakamaAgentService.AgentResponse> SetAgentCategoryMarketAsync(object filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgentWebService/SetAgentTournamentMarket", ReplyAction="http://tempuri.org/IAgentWebService/SetAgentTournamentMarketResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.SystemPlataform))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.SystemPlataformList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.SystemPlataform[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketCategoryGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketTournamentGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketSport))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketLimit[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketLimit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketCategory))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketTournament))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketSportFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketGroupFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketLimitFilter[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketLimitFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketCategoryFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketTournamentFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.HeaderResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.ErrorResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketSportGroupFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketCategoryGroupFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketTournamentGroupFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketSportGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentSettingFilter[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentSettingFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentFilter[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.Agent))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.Agent[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentSetting))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentSettingList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentSetting[]))]
        System.Threading.Tasks.Task<NakamaAgentService.AgentResponse> SetAgentTournamentMarketAsync(object filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgentWebService/GetAgentSettingByAgentID", ReplyAction="http://tempuri.org/IAgentWebService/GetAgentSettingByAgentIDResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.SystemPlataform))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.SystemPlataformList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.SystemPlataform[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketCategoryGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketTournamentGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketSport))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketLimit[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketLimit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketCategory))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketTournament))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketSportFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketGroupFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketLimitFilter[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketLimitFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketCategoryFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketTournamentFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.HeaderResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.ErrorResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketSportGroupFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketCategoryGroupFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketTournamentGroupFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketSportGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentSettingFilter[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentSettingFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentFilter[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.Agent))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.Agent[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentSetting))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentSettingList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentSetting[]))]
        System.Threading.Tasks.Task<NakamaAgentService.AgentResponse> GetAgentSettingByAgentIDAsync(object filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgentWebService/SetAgentSettingByAgentID", ReplyAction="http://tempuri.org/IAgentWebService/SetAgentSettingByAgentIDResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.SystemPlataform))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.SystemPlataformList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.SystemPlataform[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketCategoryGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketTournamentGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketSport))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketLimit[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketLimit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketCategory))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketTournament))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketSportFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketGroupFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketLimitFilter[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketLimitFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketCategoryFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.MarketTournamentFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.HeaderResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.ErrorResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketSportGroupFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketCategoryGroupFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketTournamentGroupFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentMarketSportGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentSettingFilter[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentSettingFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentFilter[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.Agent))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.Agent[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentSetting))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentSettingList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaAgentService.AgentSetting[]))]
        System.Threading.Tasks.Task<NakamaAgentService.AgentResponse> SetAgentSettingByAgentIDAsync(object filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgentWebService/GetSystemPlataform", ReplyAction="http://tempuri.org/IAgentWebService/GetSystemPlataformResponse")]
        System.Threading.Tasks.Task<NakamaAgentService.AgentResponse> GetSystemPlataformAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public interface IAgentWebServiceChannel : NakamaAgentService.IAgentWebService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public partial class AgentWebServiceClient : System.ServiceModel.ClientBase<NakamaAgentService.IAgentWebService>, NakamaAgentService.IAgentWebService
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AgentWebServiceClient() : 
                base(AgentWebServiceClient.GetDefaultBinding(), AgentWebServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IAgentWebService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AgentWebServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(AgentWebServiceClient.GetBindingForEndpoint(endpointConfiguration), AgentWebServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AgentWebServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AgentWebServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AgentWebServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AgentWebServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AgentWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<NakamaAgentService.AgentResponse> GetAgentAsync(object filter)
        {
            return base.Channel.GetAgentAsync(filter);
        }
        
        public System.Threading.Tasks.Task<NakamaAgentService.AgentResponse> GetMasterAgentsAsync(object filter)
        {
            return base.Channel.GetMasterAgentsAsync(filter);
        }
        
        public System.Threading.Tasks.Task<NakamaAgentService.AgentResponse> GetSubAgentsAsync(object filter)
        {
            return base.Channel.GetSubAgentsAsync(filter);
        }
        
        public System.Threading.Tasks.Task<NakamaAgentService.MarketResponse> GetAgentSportMarketAsync(object filter)
        {
            return base.Channel.GetAgentSportMarketAsync(filter);
        }
        
        public System.Threading.Tasks.Task<NakamaAgentService.MarketResponse> GetAgentCategoryMarketAsync(object filter)
        {
            return base.Channel.GetAgentCategoryMarketAsync(filter);
        }
        
        public System.Threading.Tasks.Task<NakamaAgentService.MarketResponse> GetAgentTournamentMarketAsync(object filter)
        {
            return base.Channel.GetAgentTournamentMarketAsync(filter);
        }
        
        public System.Threading.Tasks.Task<NakamaAgentService.AgentResponse> SetAgentSportMarketAsync(object filter)
        {
            return base.Channel.SetAgentSportMarketAsync(filter);
        }
        
        public System.Threading.Tasks.Task<NakamaAgentService.AgentResponse> SetAgentCategoryMarketAsync(object filter)
        {
            return base.Channel.SetAgentCategoryMarketAsync(filter);
        }
        
        public System.Threading.Tasks.Task<NakamaAgentService.AgentResponse> SetAgentTournamentMarketAsync(object filter)
        {
            return base.Channel.SetAgentTournamentMarketAsync(filter);
        }
        
        public System.Threading.Tasks.Task<NakamaAgentService.AgentResponse> GetAgentSettingByAgentIDAsync(object filter)
        {
            return base.Channel.GetAgentSettingByAgentIDAsync(filter);
        }
        
        public System.Threading.Tasks.Task<NakamaAgentService.AgentResponse> SetAgentSettingByAgentIDAsync(object filter)
        {
            return base.Channel.SetAgentSettingByAgentIDAsync(filter);
        }
        
        public System.Threading.Tasks.Task<NakamaAgentService.AgentResponse> GetSystemPlataformAsync()
        {
            return base.Channel.GetSystemPlataformAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IAgentWebService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IAgentWebService))
            {
                return new System.ServiceModel.EndpointAddress("http://nakama-webservice.ganaobrava.net/AgentWebService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return AgentWebServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IAgentWebService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return AgentWebServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IAgentWebService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IAgentWebService,
        }
    }
}
