//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NakamaCommonService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SportListResponse", Namespace="http://schemas.datacontract.org/2004/07/Nakama.Extension.Shared.Sport")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaCommonService.PlayerFilter[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaCommonService.PlayerFilter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaCommonService.PlayerSettingFilter[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaCommonService.PlayerSettingFilter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaCommonService.AgentFilter[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaCommonService.AgentFilter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaCommonService.AgentSettingFilter[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaCommonService.AgentSettingFilter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaCommonService.LimitFilter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaCommonService.LimitResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaCommonService.HeaderResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaCommonService.ErrorResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaCommonService.MarketSport))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaCommonService.MarketGroup))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaCommonService.MarketLimit[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaCommonService.MarketLimit))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaCommonService.MarketCategory))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaCommonService.MarketTournament))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaCommonService.SportList))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaCommonService.Sport[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaCommonService.Sport))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaCommonService.Category[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaCommonService.Category))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaCommonService.Tournament[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaCommonService.Tournament))]
    public partial class SportListResponse : object
    {
        
        private NakamaCommonService.HeaderResponse HeaderField;
        
        private object ResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NakamaCommonService.HeaderResponse Header
        {
            get
            {
                return this.HeaderField;
            }
            set
            {
                this.HeaderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HeaderResponse", Namespace="http://schemas.datacontract.org/2004/07/Nakama.Extension.Shared")]
    public partial class HeaderResponse : object
    {
        
        private NakamaCommonService.ErrorResponse ErrorField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NakamaCommonService.ErrorResponse Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success
        {
            get
            {
                return this.SuccessField;
            }
            set
            {
                this.SuccessField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerFilter", Namespace="http://schemas.datacontract.org/2004/07/Nakama.Extension.Shared.Player")]
    public partial class PlayerFilter : object
    {
        
        private string AgentIDField;
        
        private int AgentSystemIDField;
        
        private string HostPlayerIDField;
        
        private string PlayerAccountNumberField;
        
        private int PlayerIDField;
        
        private NakamaCommonService.PlayerSettingFilter[] PlayerSettingsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AgentID
        {
            get
            {
                return this.AgentIDField;
            }
            set
            {
                this.AgentIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AgentSystemID
        {
            get
            {
                return this.AgentSystemIDField;
            }
            set
            {
                this.AgentSystemIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HostPlayerID
        {
            get
            {
                return this.HostPlayerIDField;
            }
            set
            {
                this.HostPlayerIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlayerAccountNumber
        {
            get
            {
                return this.PlayerAccountNumberField;
            }
            set
            {
                this.PlayerAccountNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PlayerID
        {
            get
            {
                return this.PlayerIDField;
            }
            set
            {
                this.PlayerIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NakamaCommonService.PlayerSettingFilter[] PlayerSettings
        {
            get
            {
                return this.PlayerSettingsField;
            }
            set
            {
                this.PlayerSettingsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerSettingFilter", Namespace="http://schemas.datacontract.org/2004/07/Nakama.Extension.Shared.Player")]
    public partial class PlayerSettingFilter : object
    {
        
        private string PlayerSettingValueField;
        
        private int PropertyIDField;
        
        private string PropertyNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlayerSettingValue
        {
            get
            {
                return this.PlayerSettingValueField;
            }
            set
            {
                this.PlayerSettingValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PropertyID
        {
            get
            {
                return this.PropertyIDField;
            }
            set
            {
                this.PropertyIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PropertyName
        {
            get
            {
                return this.PropertyNameField;
            }
            set
            {
                this.PropertyNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AgentFilter", Namespace="http://schemas.datacontract.org/2004/07/Nakama.Extension.Shared.Agent")]
    public partial class AgentFilter : object
    {
        
        private string AgentIDField;
        
        private NakamaCommonService.AgentSettingFilter[] AgentSettingsField;
        
        private int AgentSystemIDField;
        
        private string AgentTypeField;
        
        private NakamaCommonService.AgentFilter[] SubAgentsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AgentID
        {
            get
            {
                return this.AgentIDField;
            }
            set
            {
                this.AgentIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NakamaCommonService.AgentSettingFilter[] AgentSettings
        {
            get
            {
                return this.AgentSettingsField;
            }
            set
            {
                this.AgentSettingsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AgentSystemID
        {
            get
            {
                return this.AgentSystemIDField;
            }
            set
            {
                this.AgentSystemIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AgentType
        {
            get
            {
                return this.AgentTypeField;
            }
            set
            {
                this.AgentTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NakamaCommonService.AgentFilter[] SubAgents
        {
            get
            {
                return this.SubAgentsField;
            }
            set
            {
                this.SubAgentsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AgentSettingFilter", Namespace="http://schemas.datacontract.org/2004/07/Nakama.Extension.Shared.Agent")]
    public partial class AgentSettingFilter : object
    {
        
        private string AgentIDField;
        
        private int AgentSettingIDField;
        
        private string AgentSettingValueField;
        
        private int PropertyIDField;
        
        private string PropertyNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AgentID
        {
            get
            {
                return this.AgentIDField;
            }
            set
            {
                this.AgentIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AgentSettingID
        {
            get
            {
                return this.AgentSettingIDField;
            }
            set
            {
                this.AgentSettingIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AgentSettingValue
        {
            get
            {
                return this.AgentSettingValueField;
            }
            set
            {
                this.AgentSettingValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PropertyID
        {
            get
            {
                return this.PropertyIDField;
            }
            set
            {
                this.PropertyIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PropertyName
        {
            get
            {
                return this.PropertyNameField;
            }
            set
            {
                this.PropertyNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LimitFilter", Namespace="http://schemas.datacontract.org/2004/07/Nakama.Extension.Shared.Common")]
    public partial class LimitFilter : object
    {
        
        private int AgentSystemIDField;
        
        private NakamaCommonService.AgentFilter[] AgentsField;
        
        private float MaxBetField;
        
        private float MaxWinField;
        
        private NakamaCommonService.PlayerFilter[] PlayersField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AgentSystemID
        {
            get
            {
                return this.AgentSystemIDField;
            }
            set
            {
                this.AgentSystemIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NakamaCommonService.AgentFilter[] Agents
        {
            get
            {
                return this.AgentsField;
            }
            set
            {
                this.AgentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float MaxBet
        {
            get
            {
                return this.MaxBetField;
            }
            set
            {
                this.MaxBetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float MaxWin
        {
            get
            {
                return this.MaxWinField;
            }
            set
            {
                this.MaxWinField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NakamaCommonService.PlayerFilter[] Players
        {
            get
            {
                return this.PlayersField;
            }
            set
            {
                this.PlayersField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LimitResponse", Namespace="http://schemas.datacontract.org/2004/07/Nakama.Extension.Shared.Common")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaCommonService.PlayerFilter[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaCommonService.PlayerFilter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaCommonService.PlayerSettingFilter[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaCommonService.PlayerSettingFilter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaCommonService.AgentFilter[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaCommonService.AgentFilter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaCommonService.AgentSettingFilter[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaCommonService.AgentSettingFilter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaCommonService.LimitFilter))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaCommonService.HeaderResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaCommonService.ErrorResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaCommonService.SportListResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaCommonService.MarketSport))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaCommonService.MarketGroup))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaCommonService.MarketLimit[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaCommonService.MarketLimit))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaCommonService.MarketCategory))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaCommonService.MarketTournament))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaCommonService.SportList))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaCommonService.Sport[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaCommonService.Sport))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaCommonService.Category[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaCommonService.Category))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaCommonService.Tournament[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaCommonService.Tournament))]
    public partial class LimitResponse : object
    {
        
        private NakamaCommonService.HeaderResponse HeaderField;
        
        private object ResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NakamaCommonService.HeaderResponse Header
        {
            get
            {
                return this.HeaderField;
            }
            set
            {
                this.HeaderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorResponse", Namespace="http://schemas.datacontract.org/2004/07/Nakama.Extension.Shared")]
    public partial class ErrorResponse : object
    {
        
        private int ErrorCodeField;
        
        private string ErrorMessageField;
        
        private string MethodNameField;
        
        private string SourceField;
        
        private string StackTraceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MethodName
        {
            get
            {
                return this.MethodNameField;
            }
            set
            {
                this.MethodNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source
        {
            get
            {
                return this.SourceField;
            }
            set
            {
                this.SourceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace
        {
            get
            {
                return this.StackTraceField;
            }
            set
            {
                this.StackTraceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MarketSport", Namespace="http://schemas.datacontract.org/2004/07/Nakama.Core.Model.Market")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaCommonService.MarketCategory))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaCommonService.MarketTournament))]
    public partial class MarketSport : NakamaCommonService.MarketGroup
    {
        
        private int SportIDField;
        
        private string SportsNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SportID
        {
            get
            {
                return this.SportIDField;
            }
            set
            {
                this.SportIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SportsName
        {
            get
            {
                return this.SportsNameField;
            }
            set
            {
                this.SportsNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MarketGroup", Namespace="http://schemas.datacontract.org/2004/07/Nakama.Core.Model.Market")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaCommonService.MarketSport))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaCommonService.MarketCategory))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaCommonService.MarketTournament))]
    public partial class MarketGroup : object
    {
        
        private int AgentSystemIDField;
        
        private bool IsForAllPlayersField;
        
        private bool IsForAllSubAgentsField;
        
        private NakamaCommonService.MarketLimit[] LimitsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AgentSystemID
        {
            get
            {
                return this.AgentSystemIDField;
            }
            set
            {
                this.AgentSystemIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsForAllPlayers
        {
            get
            {
                return this.IsForAllPlayersField;
            }
            set
            {
                this.IsForAllPlayersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsForAllSubAgents
        {
            get
            {
                return this.IsForAllSubAgentsField;
            }
            set
            {
                this.IsForAllSubAgentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NakamaCommonService.MarketLimit[] Limits
        {
            get
            {
                return this.LimitsField;
            }
            set
            {
                this.LimitsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MarketLimit", Namespace="http://schemas.datacontract.org/2004/07/Nakama.Core.Model.Market")]
    public partial class MarketLimit : object
    {
        
        private bool IsActiveField;
        
        private int MarketIDField;
        
        private string MarketNameField;
        
        private double MaxBetField;
        
        private double MaxWinField;
        
        private int SegmentIDField;
        
        private string SegmentNameField;
        
        private string SegmentShortNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive
        {
            get
            {
                return this.IsActiveField;
            }
            set
            {
                this.IsActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MarketID
        {
            get
            {
                return this.MarketIDField;
            }
            set
            {
                this.MarketIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MarketName
        {
            get
            {
                return this.MarketNameField;
            }
            set
            {
                this.MarketNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MaxBet
        {
            get
            {
                return this.MaxBetField;
            }
            set
            {
                this.MaxBetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MaxWin
        {
            get
            {
                return this.MaxWinField;
            }
            set
            {
                this.MaxWinField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SegmentID
        {
            get
            {
                return this.SegmentIDField;
            }
            set
            {
                this.SegmentIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SegmentName
        {
            get
            {
                return this.SegmentNameField;
            }
            set
            {
                this.SegmentNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SegmentShortName
        {
            get
            {
                return this.SegmentShortNameField;
            }
            set
            {
                this.SegmentShortNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MarketCategory", Namespace="http://schemas.datacontract.org/2004/07/Nakama.Core.Model.Market")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NakamaCommonService.MarketTournament))]
    public partial class MarketCategory : NakamaCommonService.MarketSport
    {
        
        private int CategoryIDField;
        
        private string CategoryNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryID
        {
            get
            {
                return this.CategoryIDField;
            }
            set
            {
                this.CategoryIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryName
        {
            get
            {
                return this.CategoryNameField;
            }
            set
            {
                this.CategoryNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MarketTournament", Namespace="http://schemas.datacontract.org/2004/07/Nakama.Core.Model.Market")]
    public partial class MarketTournament : NakamaCommonService.MarketCategory
    {
        
        private int TournamentIDField;
        
        private string TournamentNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TournamentID
        {
            get
            {
                return this.TournamentIDField;
            }
            set
            {
                this.TournamentIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TournamentName
        {
            get
            {
                return this.TournamentNameField;
            }
            set
            {
                this.TournamentNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SportList", Namespace="http://schemas.datacontract.org/2004/07/Nakama.Core.Model.Common")]
    public partial class SportList : object
    {
        
        private NakamaCommonService.Sport[] SportsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NakamaCommonService.Sport[] Sports
        {
            get
            {
                return this.SportsField;
            }
            set
            {
                this.SportsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sport", Namespace="http://schemas.datacontract.org/2004/07/Nakama.Core.Model.Common")]
    public partial class Sport : object
    {
        
        private NakamaCommonService.Category[] CategoriesField;
        
        private int SportIDField;
        
        private string SportsNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NakamaCommonService.Category[] Categories
        {
            get
            {
                return this.CategoriesField;
            }
            set
            {
                this.CategoriesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SportID
        {
            get
            {
                return this.SportIDField;
            }
            set
            {
                this.SportIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SportsName
        {
            get
            {
                return this.SportsNameField;
            }
            set
            {
                this.SportsNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/Nakama.Core.Model.Common")]
    public partial class Category : object
    {
        
        private int CategoryIDField;
        
        private string CategoryNameField;
        
        private NakamaCommonService.Tournament[] TournamentsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryID
        {
            get
            {
                return this.CategoryIDField;
            }
            set
            {
                this.CategoryIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryName
        {
            get
            {
                return this.CategoryNameField;
            }
            set
            {
                this.CategoryNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NakamaCommonService.Tournament[] Tournaments
        {
            get
            {
                return this.TournamentsField;
            }
            set
            {
                this.TournamentsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tournament", Namespace="http://schemas.datacontract.org/2004/07/Nakama.Core.Model.Common")]
    public partial class Tournament : object
    {
        
        private int TournamentIDField;
        
        private string TournamentNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TournamentID
        {
            get
            {
                return this.TournamentIDField;
            }
            set
            {
                this.TournamentIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TournamentName
        {
            get
            {
                return this.TournamentNameField;
            }
            set
            {
                this.TournamentNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NakamaCommonService.ICommonWebService")]
    public interface ICommonWebService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonWebService/GetSportList", ReplyAction="http://tempuri.org/ICommonWebService/GetSportListResponse")]
        System.Threading.Tasks.Task<NakamaCommonService.SportListResponse> GetSportListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonWebService/SetLimitAmount", ReplyAction="http://tempuri.org/ICommonWebService/SetLimitAmountResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaCommonService.PlayerFilter[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaCommonService.PlayerFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaCommonService.PlayerSettingFilter[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaCommonService.PlayerSettingFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaCommonService.AgentFilter[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaCommonService.AgentFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaCommonService.AgentSettingFilter[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaCommonService.AgentSettingFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaCommonService.LimitFilter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaCommonService.LimitResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaCommonService.HeaderResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaCommonService.ErrorResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaCommonService.SportListResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaCommonService.MarketSport))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaCommonService.MarketGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaCommonService.MarketLimit[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaCommonService.MarketLimit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaCommonService.MarketCategory))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaCommonService.MarketTournament))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaCommonService.SportList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaCommonService.Sport[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaCommonService.Sport))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaCommonService.Category[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaCommonService.Category))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaCommonService.Tournament[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NakamaCommonService.Tournament))]
        System.Threading.Tasks.Task<NakamaCommonService.LimitResponse> SetLimitAmountAsync(object filter);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public interface ICommonWebServiceChannel : NakamaCommonService.ICommonWebService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public partial class CommonWebServiceClient : System.ServiceModel.ClientBase<NakamaCommonService.ICommonWebService>, NakamaCommonService.ICommonWebService
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CommonWebServiceClient() : 
                base(CommonWebServiceClient.GetDefaultBinding(), CommonWebServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ICommonWebService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CommonWebServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(CommonWebServiceClient.GetBindingForEndpoint(endpointConfiguration), CommonWebServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CommonWebServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CommonWebServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CommonWebServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CommonWebServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CommonWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<NakamaCommonService.SportListResponse> GetSportListAsync()
        {
            return base.Channel.GetSportListAsync();
        }
        
        public System.Threading.Tasks.Task<NakamaCommonService.LimitResponse> SetLimitAmountAsync(object filter)
        {
            return base.Channel.SetLimitAmountAsync(filter);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICommonWebService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICommonWebService))
            {
                return new System.ServiceModel.EndpointAddress("http://nakama-webservice.ganaobrava.net/CommonWebService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CommonWebServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ICommonWebService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CommonWebServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ICommonWebService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ICommonWebService,
        }
    }
}
